### ISSUE TITLE
Are all dependencies required to run the software?

### ISSUE THREAD

**Issue by MatthewFlamm** [mendezVKI/SPICY_VKI#3]
A lot of packages are installed when doing `pip install spicy-vki` that do not look neccessary for an end user, for example `numpydoc`, `sphinx`, `sphinxcontrib-serializinghtml`.  Consider removing `numpydoc` and any other non-needed packages from:

https://github.com/mendezVKI/SPICY_VKI/blob/f4a2a3376eeeef1e32471061c75b378d5ae4e131/spicy_vki/setup.py#L16-L24

**Comment by MatthewFlamm** [comment]
ipython, numpydoc, and matplotlib all look to me only to be related to documentation building, but I haven't tested thoroughly.

**Comment by MatthewFlamm** [comment]
Some of these dependencies are not be required for the package itself, but are used in the tutorials or documentation building.  In that case, there should be separate instructions for installing the packages or maybe a `requirements.txt` file that is available for installing the packages for the tutorials.  Another option would be to use optional dependencies like `pip install spciy-vki[tutorial]`.

**Comment by mendezVKI** [comment]
I removed "numpydoc>=1.1.0". Concerning the tutorials, we followed your suggestion and created an installation with optional dependencies. This was also updated in the documentation.
