### ISSUE TITLE
Tutorials require a clone of this repo

### ISSUE THREAD

**Issue by MatthewFlamm** [mendezVKI/SPICY_VKI#5]
The tutorials currently require cloning this repo.  This makes the tutorials less portable to modify using a pip installed version of the package.  The tutorials should instead use the installed version of this package.

See this example:
https://github.com/mendezVKI/SPICY_VKI/blob/f4a2a3376eeeef1e32471061c75b378d5ae4e131/Tutorials/Tutorial_1_Laplace_Equation.ipynb#L33-L34

**Comment by MatthewFlamm** [comment]
More importantly, the installation instructions do not mention this as a requirement for running the tutorials.  If the tutorials are made to use the installed version, then additional installation instructions for the tutorials become easier.  Also see #3.

**Comment by mendezVKI** [comment]
The dependency issue is solved. Concerning the tutorials, indeed these should be cloned from the repository. We added one more information concerning the installation in the README.md file, mentioning explicitly that tutorials can be found in the github repository.
