### ISSUE TITLE
installation instructions in documentation typo

### ISSUE THREAD

**Issue by MatthewFlamm** [mendezVKI/SPICY_VKI#9]
As in #4, the following line

https://github.com/mendezVKI/SPICY_VKI/blob/31c54b3005ff2adccca1e80aa643b8406fc6ac1d/spicy_vki/docs/source/installation.rst?plain=1#L7

Needs to be

     $ pip install spicy-vki==1.0.0

See https://packaging.python.org/en/latest/specifications/version-specifiers/#id4

There is a line below this that also needs to be updated.

**Comment by MatthewFlamm** [comment]
Actually this version is already out of date with your changes.  I recommend just removing the version entirely. That is:

```
 $ pip install spicy-vki
```

just like you have in the readme.

**Comment by mendezVKI** [comment]
Solved !
